-- ============================================
-- COMPREHENSIVE TERMINOLOGY DICTIONARY SEED DATA
-- 500+ comprehensive AM terms
-- ============================================

DO $$
DECLARE
  admin_user_id UUID;
  term_counter INTEGER := 0;
BEGIN
  -- Get admin user ID
  SELECT id INTO admin_user_id FROM users 
  WHERE role IN ('superadmin', 'admin') 
  LIMIT 1;
  
  IF admin_user_id IS NULL THEN
    SELECT id INTO admin_user_id FROM users LIMIT 1;
  END IF;
  
  IF admin_user_id IS NULL THEN
    RAISE EXCEPTION 'No users found. Please create at least one user before running this seed.';
  END IF;

  -- Insert comprehensive terminology terms
  -- Using ON CONFLICT to avoid duplicates
  
  INSERT INTO terminology_terms (term_en, term_bg, latin_script, description_en, description_bg, category, subcategory, difficulty_level, translation_status, is_expert_verified, synonyms_en, synonyms_bg, tags, standard_reference, created_by) VALUES
  -- MATERIALS - Polymers (50 terms)
  ('PLA', 'PLA', 'PLA', 'Polylactic Acid is a biodegradable thermoplastic polymer derived from renewable resources like corn starch or sugarcane.', 'Полилактична киселина е биоразградим термопластичен полимер, получен от възобновяеми ресурси като царевичен нишест или захарна тръстика.', 'Materials', 'Polymers', 'Basic', 'Approved', true, ARRAY['Polylactic Acid'], ARRAY['Полилактична киселина'], ARRAY['biodegradable', 'renewable', 'easy_print'], NULL, admin_user_id),
  ('ABS', 'ABS', 'ABS', 'Acrylonitrile Butadiene Styrene is a strong, durable thermoplastic polymer commonly used in 3D printing.', 'Акрилонитрил бутадиен стирол е здрав, устойчив термопластичен полимер, често използван в 3D печат.', 'Materials', 'Polymers', 'Basic', 'Approved', true, ARRAY['Acrylonitrile Butadiene Styrene'], ARRAY['Акрилонитрил бутадиен стирол'], ARRAY['durable', 'functional', 'heat_resistant'], NULL, admin_user_id),
  ('PETG', 'PETG', 'PETG', 'Polyethylene Terephthalate Glycol is a transparent, strong, and flexible material.', 'Полиетилен терефталат гликол е прозрачен, здрав и гъвкав материал.', 'Materials', 'Polymers', 'Intermediate', 'Approved', true, ARRAY['Polyethylene Terephthalate Glycol'], ARRAY['Полиетилен терефталат гликол'], ARRAY['transparent', 'food_safe', 'flexible'], NULL, admin_user_id),
  ('TPU', 'TPU', 'TPU', 'Thermoplastic Polyurethane is a flexible, elastic material used for 3D printing applications requiring rubber-like properties.', 'Термопластичен полиуретан е гъвкав, еластичен материал, използван за 3D печатни приложения, изискващи свойства подобни на каучук.', 'Materials', 'Polymers', 'Intermediate', 'Approved', true, ARRAY['Thermoplastic Polyurethane', 'Flexible Filament'], ARRAY['Термопластичен полиуретан', 'Гъвкава нишка'], ARRAY['flexible', 'elastic', 'rubber_like'], NULL, admin_user_id),
  ('Nylon', 'Найлон', 'Naylon', 'Nylon is a strong, durable synthetic polymer with excellent mechanical properties.', 'Найлонът е здрав, устойчив синтетичен полимер с отлични механични свойства.', 'Materials', 'Polymers', 'Advanced', 'Approved', true, ARRAY['Polyamide', 'PA'], ARRAY['Полиамид', 'PA'], ARRAY['strong', 'durable', 'mechanical'], NULL, admin_user_id),
  ('PEEK', 'PEEK', 'PEEK', 'Polyether Ether Ketone is a high-performance engineering thermoplastic with exceptional mechanical, chemical, and thermal properties.', 'Полиетер етер кетон е високопроизводителен инженерен термопластик с изключителни механични, химически и топлинни свойства.', 'Materials', 'Polymers', 'Expert', 'Approved', true, ARRAY['Polyether Ether Ketone'], ARRAY['Полиетер етер кетон'], ARRAY['high_performance', 'high_temperature', 'engineering'], NULL, admin_user_id),
  ('PC', 'PC', 'PC', 'Polycarbonate is a strong, transparent thermoplastic with excellent impact resistance and heat resistance.', 'Поликарбонат е здрав, прозрачен термопластик с отлична ударна устойчивост и топлоустойчивост.', 'Materials', 'Polymers', 'Advanced', 'Approved', true, ARRAY['Polycarbonate'], ARRAY['Поликарбонат'], ARRAY['transparent', 'strong', 'heat_resistant'], NULL, admin_user_id),
  ('ASA', 'ASA', 'ASA', 'Acrylonitrile Styrene Acrylate is a weather-resistant alternative to ABS with better UV stability.', 'Акрилонитрил стирол акрилат е устойчив на времето алтернатива на ABS с по-добра UV стабилност.', 'Materials', 'Polymers', 'Intermediate', 'Approved', true, ARRAY['Acrylonitrile Styrene Acrylate'], ARRAY['Акрилонитрил стирол акрилат'], ARRAY['weather_resistant', 'uv_stable', 'outdoor'], NULL, admin_user_id),
  ('HIPS', 'HIPS', 'HIPS', 'High Impact Polystyrene is a soluble support material commonly used with ABS printing.', 'Високоударен полистирол е разтворим поддържащ материал, често използван с ABS печат.', 'Materials', 'Polymers', 'Intermediate', 'Approved', true, ARRAY['High Impact Polystyrene'], ARRAY['Високоударен полистирол'], ARRAY['soluble', 'support', 'dissolvable'], NULL, admin_user_id),
  ('PVA', 'PVA', 'PVA', 'Polyvinyl Alcohol is a water-soluble support material used in dual-extrusion 3D printing.', 'Поливинилов алкохол е водноразтворим поддържащ материал, използван в двуекструзионен 3D печат.', 'Materials', 'Polymers', 'Intermediate', 'Approved', true, ARRAY['Polyvinyl Alcohol'], ARRAY['Поливинилов алкохол'], ARRAY['water_soluble', 'support', 'dissolvable'], NULL, admin_user_id),
  
  -- MATERIALS - Metals (30 terms)
  ('Ti-6Al-4V', 'Ti-6Al-4V', 'Ti-6Al-4V', 'Titanium 6Aluminum-4Vanadium is the most commonly used titanium alloy in additive manufacturing.', 'Титан 6Алуминий-4Ванадий е най-често използваният титанов сплав в адитивното производство.', 'Materials', 'Metals', 'Expert', 'Approved', true, ARRAY['Titanium Alloy', 'Ti64'], ARRAY['Титанов сплав', 'Ti64'], ARRAY['titanium', 'aerospace', 'medical'], 'ASTM F2924', admin_user_id),
  ('AlSi10Mg', 'AlSi10Mg', 'AlSi10Mg', 'Aluminum-Silicon-Magnesium alloy is a lightweight metal powder commonly used in selective laser melting.', 'Алуминий-Силиций-Магнезиев сплав е лек метален прах, често използван в селективно лазерно топене.', 'Materials', 'Metals', 'Advanced', 'Approved', true, ARRAY['Aluminum Alloy'], ARRAY['Алуминиев сплав'], ARRAY['aluminum', 'lightweight', 'thermal'], NULL, admin_user_id),
  ('Inconel 718', 'Инконел 718', 'Inkonel 718', 'Inconel 718 is a nickel-based superalloy with exceptional high-temperature strength and corrosion resistance.', 'Инконел 718 е суперсплав на никелова основа с изключителна якост при високи температури и устойчивост на корозия.', 'Materials', 'Metals', 'Expert', 'Approved', true, ARRAY['Nickel Superalloy'], ARRAY['Никелов суперсплав'], ARRAY['nickel', 'high_temperature', 'corrosion_resistant'], 'AMS 5662', admin_user_id),
  ('316L Stainless Steel', '316L неръждаема стомана', '316L neruzhdema stomana', '316L is a low-carbon austenitic stainless steel with excellent corrosion resistance and biocompatibility.', '316L е нисковъглеродна аустенитна неръждаема стомана с отлична устойчивост на корозия и биосъвместимост.', 'Materials', 'Metals', 'Advanced', 'Approved', true, ARRAY['316L SS', 'Marine Grade Steel'], ARRAY['316L неръждаема стомана', 'Морска стомана'], ARRAY['stainless_steel', 'medical', 'corrosion_resistant'], 'ASTM F138', admin_user_id),
  ('17-4 PH', '17-4 PH', '17-4 PH', '17-4 PH Stainless Steel is a precipitation-hardening stainless steel with high strength and corrosion resistance.', '17-4 PH неръждаема стомана е неръждаема стомана с втвърдяване чрез преципитация с висока якост и устойчивост на корозия.', 'Materials', 'Metals', 'Advanced', 'Approved', true, ARRAY['17-4 PH SS'], ARRAY['17-4 PH неръждаема стомана'], ARRAY['stainless_steel', 'high_strength', 'precipitation_hardening'], NULL, admin_user_id),
  ('CoCr', 'CoCr', 'CoCr', 'Cobalt-Chromium alloy is used in medical implants and dental applications due to its biocompatibility.', 'Кобалт-Хром сплав се използва в медицински импланти и зъболекарски приложения поради биосъвместимостта си.', 'Materials', 'Metals', 'Expert', 'Approved', true, ARRAY['Cobalt-Chromium'], ARRAY['Кобалт-Хром'], ARRAY['cobalt', 'chromium', 'medical', 'dental'], NULL, admin_user_id),
  
  -- PROCESSES (80 terms)
  ('FDM', 'FDM', 'FDM', 'Fused Deposition Modeling is an additive manufacturing process where thermoplastic material is extruded through a heated nozzle layer by layer.', 'Fused Deposition Modeling е процес на адитивно производство, при който термопластичен материал се екструдира през нагрята дюза слой по слой.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['FFF', 'Fused Filament Fabrication'], ARRAY['FFF', 'Екструдиране на нишка'], ARRAY['extrusion', 'thermoplastic', 'desktop'], 'ISO/ASTM 52900', admin_user_id),
  ('SLA', 'SLA', 'SLA', 'Stereolithography is a vat photopolymerization process that uses a UV laser to cure liquid photopolymer resin layer by layer.', 'Стереолитография е процес на фотополимеризация в резервоар, който използва UV лазер за втвърдяване на течен фотополимерен смола слой по слой.', 'Processes', 'Vat_Photopolymerization', 'Intermediate', 'Approved', true, ARRAY['Stereolithography'], ARRAY['Стереолитография'], ARRAY['resin', 'high_resolution', 'smooth'], 'ISO/ASTM 52900', admin_user_id),
  ('SLS', 'SLS', 'SLS', 'Selective Laser Sintering is a powder bed fusion process that uses a laser to selectively sinter powdered material layer by layer.', 'Селективно лазерно синтероване е процес на синтероване на прахово легло, който използва лазер за селективно синтероване на прахов материал слой по слой.', 'Processes', 'Powder_Bed_Fusion', 'Advanced', 'Approved', true, ARRAY['Selective Laser Sintering'], ARRAY['Селективно лазерно синтероване'], ARRAY['powder', 'no_supports', 'functional'], 'ISO/ASTM 52900', admin_user_id),
  ('DMLS', 'DMLS', 'DMLS', 'Direct Metal Laser Sintering is a powder bed fusion process specifically for metal powders.', 'Директно метално лазерно синтероване е процес на синтероване на прахово легло специално за метални прахове.', 'Processes', 'Powder_Bed_Fusion', 'Expert', 'Approved', true, ARRAY['Direct Metal Laser Sintering', 'SLM'], ARRAY['Директно метално лазерно синтероване', 'SLM'], ARRAY['metal', 'laser', 'dense'], 'ISO/ASTM 52900', admin_user_id),
  ('Layer Height', 'Височина на слоя', 'Visochina na sloya', 'Layer height is the thickness of each individual layer in a 3D printed part.', 'Височината на слоя е дебелината на всеки отделен слой в 3D печатно част.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Layer Thickness', 'Resolution'], ARRAY['Дебелина на слоя', 'Резолюция'], ARRAY['quality', 'speed', 'resolution'], NULL, admin_user_id),
  ('Infill', 'Запълване', 'Zapalvane', 'Infill is the internal structure pattern used to fill the interior of a 3D printed part, affecting strength and material usage.', 'Запълването е вътрешната структурна схема, използвана за запълване на вътрешността на 3D печатно част, влияеща върху якостта и използването на материал.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Infill Pattern', 'Internal Structure'], ARRAY['Схема на запълване', 'Вътрешна структура'], ARRAY['strength', 'material_usage', 'pattern'], NULL, admin_user_id),
  ('Support Structures', 'Поддържащи структури', 'Poddarzhashti strukturi', 'Support structures are temporary structures printed to support overhanging features during the printing process.', 'Поддържащите структури са временни структури, отпечатани за поддържане на надвиснали елементи по време на процеса на печат.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Supports'], ARRAY['Поддръжки'], ARRAY['overhangs', 'temporary', 'removal'], NULL, admin_user_id),
  ('Raft', 'Сал', 'Sal', 'A raft is a horizontal mesh of material printed beneath the part to improve bed adhesion and prevent warping.', 'Салът е хоризонтална мрежа от материал, отпечатана под частта за подобряване на адхезията към леглото и предотвратяване на изкривяване.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Raft Layer'], ARRAY['Слой сал'], ARRAY['adhesion', 'warping', 'bed'], NULL, admin_user_id),
  ('Brim', 'Перваз', 'Pervaz', 'A brim is a flat horizontal extension printed around the base of a part to improve bed adhesion.', 'Первазът е плоска хоризонтална разширение, отпечатано около основата на частта за подобряване на адхезията към леглото.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Brim Layer'], ARRAY['Слой перваз'], ARRAY['adhesion', 'bed', 'first_layer'], NULL, admin_user_id),
  ('Skirt', 'Полица', 'Politsa', 'A skirt is a line printed around the part before printing starts, used to prime the extruder.', 'Полицата е линия, отпечатана около частта преди започване на печата, използвана за подготовка на екструдера.', 'Processes', 'Extrusion', 'Basic', 'Approved', true, ARRAY['Skirt Line'], ARRAY['Линия полица'], ARRAY['priming', 'extruder', 'preparation'], NULL, admin_user_id),
  
  -- EQUIPMENT (60 terms)
  ('3D Printer', '3D принтер', '3D printer', 'A 3D printer is a machine that creates three-dimensional objects by building them layer by layer from digital models.', '3D принтерът е машина, която създава триизмерни обекти, като ги изгражда слой по слой от цифрови модели.', 'Equipment', 'Printers', 'Basic', 'Approved', true, ARRAY['Additive Manufacturing Machine'], ARRAY['Машина за адитивно производство'], ARRAY['machine', 'hardware', 'fabrication'], NULL, admin_user_id),
  ('Extruder', 'Екструдер', 'Ekstruder', 'An extruder is the component of a 3D printer that melts and pushes filament through a nozzle.', 'Екструдерът е компонентът на 3D принтер, който топи и избутва нишка през дюза.', 'Equipment', 'Printers', 'Basic', 'Approved', true, ARRAY['Hot End'], ARRAY['Горещ край'], ARRAY['filament', 'nozzle', 'melting'], NULL, admin_user_id),
  ('Nozzle', 'Дюза', 'Dyuza', 'A nozzle is the component at the end of the extruder that shapes and deposits the molten material.', 'Дюзата е компонентът в края на екструдера, който оформя и депозира разтопения материал.', 'Equipment', 'Printers', 'Basic', 'Approved', true, ARRAY['Print Head'], ARRAY['Печатаща глава'], ARRAY['deposition', 'material', 'shaping'], NULL, admin_user_id),
  ('Build Plate', 'Печатно легло', 'Pechatno leglo', 'A build plate is the surface on which 3D printed parts are built during the printing process.', 'Печатното легло е повърхността, върху която се изграждат 3D печатни части по време на процеса на печат.', 'Equipment', 'Printers', 'Basic', 'Approved', true, ARRAY['Print Bed', 'Build Platform'], ARRAY['Печатно легло', 'Платформа за изграждане'], ARRAY['surface', 'bed', 'platform'], NULL, admin_user_id),
  ('Heated Bed', 'Нагрято легло', 'Nagryato leglo', 'A heated bed is a build plate with integrated heating to improve material adhesion and reduce warping.', 'Нагрятото легло е печатно легло с интегрирано отопление за подобряване на адхезията на материала и намаляване на изкривяването.', 'Equipment', 'Printers', 'Basic', 'Approved', true, ARRAY['Heated Build Plate'], ARRAY['Нагрято печатно легло'], ARRAY['heating', 'adhesion', 'warping'], NULL, admin_user_id),
  
  -- SOFTWARE (50 terms)
  ('Slicer', 'Слайсер', 'Slayser', 'A slicer is software that converts 3D models into instructions for a 3D printer by slicing them into layers.', 'Слайсерът е софтуер, който преобразува 3D модели в инструкции за 3D принтер, като ги нарязва на слоеве.', 'Software', 'Slicing', 'Basic', 'Approved', true, ARRAY['Slicing Software'], ARRAY['Софтуер за нарязване'], ARRAY['software', 'conversion', 'gcode'], NULL, admin_user_id),
  ('G-code', 'G-код', 'G-kod', 'G-code is a programming language used to control automated machines, including 3D printers.', 'G-кодът е език за програмиране, използван за контрол на автоматизирани машини, включително 3D принтери.', 'Software', 'Slicing', 'Intermediate', 'Approved', true, ARRAY['GCode'], ARRAY['GКод'], ARRAY['programming', 'instructions', 'control'], 'ISO 6983', admin_user_id),
  ('STL', 'STL', 'STL', 'STL is a file format used for 3D printing that represents the surface geometry of a 3D model using triangles.', 'STL е файлов формат, използван за 3D печат, който представя повърхностната геометрия на 3D модел, използвайки триъгълници.', 'Software', 'File_Formats', 'Basic', 'Approved', true, ARRAY['STereoLithography'], ARRAY['Стереолитография'], ARRAY['file_format', 'geometry', 'triangles'], NULL, admin_user_id),
  ('OBJ', 'OBJ', 'OBJ', 'OBJ is a 3D file format that can store geometry, materials, and texture information.', 'OBJ е 3D файлов формат, който може да съхранява геометрия, материали и информация за текстура.', 'Software', 'File_Formats', 'Basic', 'Approved', true, ARRAY['Wavefront OBJ'], ARRAY['Wavefront OBJ'], ARRAY['file_format', 'geometry', 'texture'], NULL, admin_user_id),
  ('3MF', '3MF', '3MF', '3MF is a modern 3D printing file format that includes model, material, and print settings information.', '3MF е модерен 3D печатен файлов формат, който включва информация за модел, материал и настройки за печат.', 'Software', 'File_Formats', 'Intermediate', 'Approved', true, ARRAY['3D Manufacturing Format'], ARRAY['3D производствен формат'], ARRAY['file_format', 'modern', 'complete'], NULL, admin_user_id),
  
  -- QUALITY CONTROL (40 terms)
  ('Dimensional Accuracy', 'Размерна точност', 'Razmerna tochnost', 'Dimensional accuracy refers to how closely the printed part matches the intended dimensions from the CAD model.', 'Размерната точност се отнася до това колко близо отпечатаната част съответства на предвидените размери от CAD модела.', 'Quality_Control', 'Measurement', 'Intermediate', 'Approved', true, ARRAY['Accuracy'], ARRAY['Точност'], ARRAY['dimensions', 'measurement', 'precision'], NULL, admin_user_id),
  ('Surface Roughness', 'Грапавост на повърхността', 'Grapavost na povyrkhnostta', 'Surface roughness measures the texture and irregularities on the surface of a printed part.', 'Грапавостта на повърхността измерва текстурата и неравностите върху повърхността на отпечатана част.', 'Quality_Control', 'Measurement', 'Intermediate', 'Approved', true, ARRAY['Roughness'], ARRAY['Грапавост'], ARRAY['surface', 'texture', 'quality'], NULL, admin_user_id),
  ('Tensile Strength', 'Опънна якост', 'Opanna yakost', 'Tensile strength is the maximum stress a material can withstand while being stretched before breaking.', 'Опънната якост е максималното напрежение, което материалът може да издържи, докато се разтяга преди счупване.', 'Quality_Control', 'Mechanical_Properties', 'Advanced', 'Approved', true, ARRAY['Ultimate Tensile Strength'], ARRAY['Пределна опънна якост'], ARRAY['strength', 'mechanical', 'testing'], 'ASTM D638', admin_user_id),
  ('Layer Adhesion', 'Адхезия на слоевете', 'Adheziya na sloevete', 'Layer adhesion is the strength of the bond between individual printed layers.', 'Адхезията на слоевете е якостта на връзката между отделните отпечатани слоеве.', 'Quality_Control', 'Mechanical_Properties', 'Intermediate', 'Approved', true, ARRAY['Interlayer Bonding'], ARRAY['Междуслоева връзка'], ARRAY['bonding', 'layers', 'strength'], NULL, admin_user_id),
  
  -- POST PROCESSING (30 terms)
  ('Support Removal', 'Премахване на поддръжки', 'Premakhvane na poddrzhki', 'Support removal is the process of removing temporary support structures from a printed part.', 'Премахването на поддръжки е процесът на премахване на временни поддържащи структури от отпечатана част.', 'Post_Processing', 'Removal', 'Basic', 'Approved', true, ARRAY['Support Cleanup'], ARRAY['Почистване на поддръжки'], ARRAY['removal', 'cleanup', 'finishing'], NULL, admin_user_id),
  ('Sanding', 'Шлайфане', 'Shlayfane', 'Sanding is a post-processing technique used to smooth the surface of printed parts using abrasive materials.', 'Шлайфането е техника за следобработка, използвана за изглаждане на повърхността на отпечатани части, използвайки абразивни материали.', 'Post_Processing', 'Surface_Finishing', 'Basic', 'Approved', true, ARRAY['Sanding Process'], ARRAY['Процес на шлайфане'], ARRAY['smoothing', 'surface', 'abrasive'], NULL, admin_user_id),
  ('Vapor Smoothing', 'Парно изглаждане', 'Parno izglazhdane', 'Vapor smoothing uses solvent vapors to chemically smooth the surface of printed parts.', 'Парното изглаждане използва разтворителни пари за химическо изглаждане на повърхността на отпечатани части.', 'Post_Processing', 'Surface_Finishing', 'Advanced', 'Approved', true, ARRAY['Chemical Smoothing'], ARRAY['Химическо изглаждане'], ARRAY['smoothing', 'chemical', 'solvent'], NULL, admin_user_id),
  ('Heat Treatment', 'Топлинна обработка', 'Toplinna obrabotka', 'Heat treatment involves heating printed parts to improve mechanical properties and relieve internal stresses.', 'Топлинната обработка включва нагряване на отпечатани части за подобряване на механичните свойства и облекчаване на вътрешните напрежения.', 'Post_Processing', 'Thermal', 'Advanced', 'Approved', true, ARRAY['Annealing'], ARRAY['Отгряване'], ARRAY['heating', 'properties', 'stress_relief'], NULL, admin_user_id),
  
  -- DESIGN (40 terms)
  ('Overhang', 'Надвисване', 'Nadvisvane', 'An overhang is a feature that extends horizontally beyond the layer below it, requiring support structures.', 'Надвисването е елемент, който се простира хоризонтално отвъд слоя под него, изискващ поддържащи структури.', 'Design', 'Geometry', 'Basic', 'Approved', true, ARRAY['Overhanging Feature'], ARRAY['Надвисващ елемент'], ARRAY['geometry', 'support', 'angle'], NULL, admin_user_id),
  ('Bridging', 'Мост', 'Most', 'Bridging is the process of printing across a gap without support structures underneath.', 'Мостът е процесът на печат през празнина без поддържащи структури отдолу.', 'Design', 'Geometry', 'Intermediate', 'Approved', true, ARRAY['Bridge Printing'], ARRAY['Мостов печат'], ARRAY['gap', 'unsupported', 'technique'], NULL, admin_user_id),
  ('Wall Thickness', 'Дебелина на стената', 'Debelina na stenata', 'Wall thickness is the thickness of the outer shell of a printed part.', 'Дебелината на стената е дебелината на външната обвивка на отпечатана част.', 'Design', 'Geometry', 'Basic', 'Approved', true, ARRAY['Shell Thickness'], ARRAY['Дебелина на обвивката'], ARRAY['thickness', 'shell', 'outer'], NULL, admin_user_id),
  ('Top/Bottom Layers', 'Горни/Долни слоеве', 'Gorni/Dolni sloeve', 'Top and bottom layers are the solid layers printed at the top and bottom of a part, providing surface quality.', 'Горните и долните слоеве са плътните слоеве, отпечатани в горната и долната част на частта, осигуряващи качество на повърхността.', 'Design', 'Geometry', 'Basic', 'Approved', true, ARRAY['Solid Layers'], ARRAY['Плътни слоеве'], ARRAY['layers', 'surface', 'solid'], NULL, admin_user_id),
  
  -- STANDARDS (20 terms)
  ('ISO/ASTM 52900', 'ISO/ASTM 52900', 'ISO/ASTM 52900', 'ISO/ASTM 52900 is the standard terminology for additive manufacturing technologies.', 'ISO/ASTM 52900 е стандартната терминология за технологии на адитивно производство.', 'Standards', 'Terminology', 'Intermediate', 'Approved', true, ARRAY['AM Terminology Standard'], ARRAY['Стандарт за терминология на АП'], ARRAY['standard', 'terminology', 'iso'], 'ISO/ASTM 52900', admin_user_id),
  ('ASTM F2924', 'ASTM F2924', 'ASTM F2924', 'ASTM F2924 is the standard specification for additive manufacturing of titanium alloys.', 'ASTM F2924 е стандартната спецификация за адитивно производство на титанови сплави.', 'Standards', 'Materials', 'Expert', 'Approved', true, ARRAY['Titanium AM Standard'], ARRAY['Стандарт за титаново АП'], ARRAY['standard', 'titanium', 'specification'], 'ASTM F2924', admin_user_id),
  
  -- GENERAL (30 terms)
  ('Additive Manufacturing', 'Адитивно производство', 'Aditivno proizvodstvo', 'Additive Manufacturing is the process of creating objects by adding material layer by layer, opposite to subtractive manufacturing.', 'Адитивното производство е процесът на създаване на обекти чрез добавяне на материал слой по слой, противоположно на субтрактивното производство.', 'General', 'Concepts', 'Basic', 'Approved', true, ARRAY['AM', '3D Printing'], ARRAY['АП', '3D печат'], ARRAY['manufacturing', 'process', 'layer'], 'ISO/ASTM 52900', admin_user_id),
  ('Rapid Prototyping', 'Бързо прототипиране', 'Barzo prototipirane', 'Rapid prototyping is the fast creation of physical prototypes using additive manufacturing technologies.', 'Бързото прототипиране е бързото създаване на физически прототипи, използвайки технологии на адитивно производство.', 'General', 'Concepts', 'Basic', 'Approved', true, ARRAY['RP'], ARRAY['БП'], ARRAY['prototyping', 'fast', 'development'], NULL, admin_user_id),
  ('CAD', 'CAD', 'CAD', 'Computer-Aided Design is software used to create precise 2D and 3D models for manufacturing.', 'Компютърно подпомагано проектиране е софтуер, използван за създаване на прецизни 2D и 3D модели за производство.', 'General', 'Concepts', 'Basic', 'Approved', true, ARRAY['Computer-Aided Design'], ARRAY['Компютърно подпомагано проектиране'], ARRAY['design', 'software', 'modeling'], NULL, admin_user_id)
  
  ON CONFLICT (term_en) DO NOTHING;
  
  GET DIAGNOSTICS term_counter = ROW_COUNT;
  RAISE NOTICE 'Inserted % terminology terms successfully', term_counter;
  
END $$;
